import serviceCreateWarehouseMovementResource from './serviceCreateWarehouseMovementResource'
import serviceGetWarehouseMovementResources from './serviceGetWarehouseMovementResources'
import serviceGetWarehouseMovementResource from './serviceGetWarehouseMovementResource'
import serviceUpdateWarehouseMovementResource from './serviceUpdateWarehouseMovementResource'
import serviceDeleteWarehouseMovementResource from './serviceDeleteWarehouseMovementResource'

const useWarehouseMovementResources = {
  serviceCreateWarehouseMovementResource,
  serviceGetWarehouseMovementResources,
  serviceGetWarehouseMovementResource,
  serviceUpdateWarehouseMovementResource,
  serviceDeleteWarehouseMovementResource,
}

export default useWarehouseMovementResources
